## List as an array

* Python does not have an Array so it uses list to act similarly
* Array stores multiple values 

In [1]:
# create an array

names = ["Neeraj", "Shivani", "Yugal", "Karan", "Srishti"]
names

['Neeraj', 'Shivani', 'Yugal', 'Karan', 'Srishti']

In [2]:
# access different elements

print(f'1 --> {names[0]}')
print(f'2 --> {names[1]}')
print(f'3 --> {names[2]}')
print(f'4 --> {names[3]}')
print(f'5 --> {names[4]}')

1 --> Neeraj
2 --> Shivani
3 --> Yugal
4 --> Karan
5 --> Srishti


In [3]:
# length of an array

len(names)

5

In [4]:
# loop through all the elements 

for item in names:
    print(item)

Neeraj
Shivani
Yugal
Karan
Srishti


### Numpy Array

In [5]:
import numpy as np

In [6]:
# addition of two arrays

a1 = [1, 2, 4]
a2 = [2, 5, 10]

np.add(a1,a2)

array([ 3,  7, 14])

In [7]:
# multiplication of two arrays

np.multiply(a1,a2)

array([ 2, 10, 40])

In [8]:
# multiply an array with the scalar value

np.multiply(a1,2)

array([2, 4, 8])

In [9]:
# create a numpy array object

arr = np.array([[1,2,3,6],[4,5,6,7]])

In [10]:
# check the type of an array object

type(arr)

numpy.ndarray

In [11]:
# check the dimension of an array object

arr.ndim

2

In [12]:
# check shape of an array (rows,cols)

arr.shape

(2, 4)

In [13]:
# check the size of an array (no. of elements)

arr.size

8

In [14]:
# check the type of elements in array

arr.dtype

dtype('int32')

In [15]:
# Creating a 3X4 array with all zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# Create a constant value array of int type

np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [17]:
# Create a constant value array of complex type

np.full((3,4),5, dtype = "complex")

array([[5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j]])

In [18]:
# check the largest element

arr = np.array([[1,2,3,6],[4,5,6,7],[20,0,12,9]])

arr.max()

20

In [19]:
# print row-wise maximum elements

arr.max(axis = 1)

array([ 6,  7, 20])

In [20]:
# print row-wise minimum elements

arr.min(axis = 1)

array([1, 4, 0])

In [21]:
# print col-wise maximum elements

arr.max(axis = 0)

array([20,  5, 12,  9])

In [22]:
# print col-wise minimum elements

arr.min(axis = 0)

array([1, 0, 3, 6])